-- creation of tables file

CREATE TABLE categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE
);
CREATE TABLE suppliers (
    supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(100) NOT NULL,
    contact_person VARCHAR2(100),
    phone VARCHAR2(30),
    address VARCHAR2(200)
);
CREATE TABLE products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category_id INT,
    unit_price NUMBER(10, 2),
    quantity_in_stock INT,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(category_id)
);
CREATE TABLE stock_in (
    stock_in_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT,
    supplier_id INT,
    quantity INT,
    date_received DATE DEFAULT SYSDATE,
    CONSTRAINT fk_stockin_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_stockin_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);
CREATE TABLE stock_out (
    stock_out_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INT,
    quantity INT,
    recipient VARCHAR2(100),
    date_sent DATE DEFAULT SYSDATE,
    CONSTRAINT fk_stockout_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

DROP TABLE suppliers CASCADE CONSTRAINTS;